.docname {AssignmentTwo}
.theme{beaver} layout:{latex}
.doctype{paged}
.doclang{English}

.pagemargin{bottomleft}
   EMSC3025-6025

.pagemargin{topright}
    Assignment II

.include{definitions.qmd}

Changes in total water storage can be estimated from space gravity data of the **GRACE** and **GRACE Follow-On** missions.
This includes changes in:
   - Surface water
   - Soil moisture
   - Groundwater aquifers
Surface soil moisture content can be estimated using a combination of satellite missions that use **active** and/or **passive** sensors.

.whitespace{10pt}

.center
   .container width:{90%} background:{.lightblue} radius:{9pt} padding:{10pt}
      ##### Groundwater Estimation
      On the assumption that all changes in TWS are caused by changes in either soil moisture or groundwater, it becomes possible to derive groundwater changes:

         $ \Delta \text{Groundwater} = \Delta \text{TWS} – \Delta \text{Soil Moisture} $

### Questions
1. **(5 marks)** Download the GRACE/GRACE-FO monthly estimates of changes in total water storage generated by the Center of Space Research (CSR), University of Texas at Austin from:
[GRACE CSR Data](https://www2.csr.utexas.edu/grace/RL06_mascons.html). You can click on the `CSR_GRACE_GRACE-FO_RL0603_Mascons_all-corrections.nc` and download the file.

See a description of the data at: [CSR GRACE Mascons](https://www2.csr.utexas.edu/grace/RL06_mascons.html)

➡️ Derive a **time series of changes in total water storage** integrated over the **Murray–Darling Basin**.
(Hint: if this takes a long time, save the output in a text file so you don’t have to run the integration again).

2. **(5 marks)** Download the ESA Climate Change Initiative (ESACCI) **combined** soil moisture monthly product from:
[ESA CCI Data](https://catalogue.ceda.ac.uk/uuid/779f116d0477439db1874592add5848c/)

.align{center}
   .container width:{80%} alignment:{center} background:{rgb(255, 215, 215)} radius:{9pt} padding:{10pt} borderwidth:{1pt}
      *Note:* We have generate a subset of the dataset in one NetCDF file for you and placed it water-course repository in [here](https://gadopt.syd1.cdn.digitaloceanspaces.com/water-course/combined_masked_soil_moisture.nc).

➡️ Produce a **time series of changes in soil moisture** integrated over the **Murray–Darling Basin** at the same epochs as the estimates in (i).

**Important data conversion notes:**
- The ESA CCI Soil Moisture product provides volumetric soil moisture ($ m^3 \text{water}/m^3 \text{soil}$)
- You must convert this to equivalent water depth for your analysis (volumetric water content * depth)
- **Assumption**: Extend the soil data to represent the top 20 centimetres of the soil column.
- **Data limitation**: The actual measurement accuracy is only for the top 0.05 meters (5 cm) of soil. Discuss the implications of this limitation by showing the difference between the contribution if the soil data was only for the top 5 cm of the soil column. Explain why the soild moisture data cannot be used beyond 5 cm.


3. **(5 marks)** Download and plot globally **one daily file** of the ESACCI combined soil moisture daily product** from the CEDA archive catalogue.

➡️ Explain how this product is produced and discuss the **limitations of the data**.
See [ESA Soil Moisture Project](https://climate.esa.int/en/projects/soil-moisture/) and references within.


4. **(5 marks)** Produce a **time series of changes in groundwater** over the **Murray–Darling Basin** as a whole for the period **2002–2022**.
Also derive the series for the **northern** and **southern** Murray–Darling Basin separately.

(Hint: be sure to consider the different units and reference epochs of the two data products).

5. **(5 marks)** Compare the **spatial and temporal patterns** of groundwater change over the Murray–Darling Basin.

➡️ Comment on whether the estimates of groundwater change are **reliable**.

.center
   .container width:{80%} background:{.lightblue} radius:{9pt} padding:{10pt}
      ##### Submission Instructions:
      - Submit your answers through Canvas portal
      - Include your **Python notebook**.
      - Submit any **text files** created during the assignment.
